### PR TITLE
Fan algorithm

### PR DESCRIPTION
**Pull request by ken1029**
Hardware monitor NCT7904D can monitor all current fan speed and change the PWM by fan control algorithm
BMC calculate the fan speed with Open loop and Close loop.
Each algorithm will output the expected PWM value. Finally BMC choose the maximum value to update the fan speed.
The close loop will base on CPU, DIMM, and HDD temperature to calculate the fan speed.
The close loop will base on ambient temperature to calculate the fan speed. The close loop follows the PID concept as below.

### CODE REVIEW

**Comment by anoo1** [comment]
Hi @ken1029 , please submit these changes via gerrit, and we'll get the review process started to get this merged. Instructions for gerrit here:
https://github.com/openbmc/docs/blob/master/contributing.md#submitting-changes-via-gerrit-server

**Comment by ken1029** [comment]
Hi @anoo1 Do you have any experience dealing with these kinds of problems?

1.git push gerrit HEAD:refs/for/master
remote: ERROR:  In commit 1e7d58b973c54d5a5ae72dfbb57ab565c46c5a70
remote: ERROR:  committer email address ken1029@gmail.com
remote: ERROR:  does not match your user account.
remote: ERROR:
remote: ERROR:  You have not registered any email addresses.
remote: ERROR:
remote: ERROR:  To register an email address, please visit:
remote: ERROR:  https://gerrit.openbmc-project.xyz/#/settings/contact

2.Register new email
Code Review - Error
500 Internal server error

**Comment by williamspatrick** [comment]
@ken1029 - You can import your email address from Github into Gerrit with the github integration plugin we have installed:  https://gerrit.openbmc-project.xyz/plugins/github-plugin/static/account.html

**Comment by ken1029** [comment]
Hi @williamspatrick 
thanks~~i can register email :)
But there is a new problem :(

ken@ken-PowerEdge-R210-II:~/openbmc/skeleton$ git push gerrit HEAD:refs/for/master
Counting objects: 23, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (9/9), done.
Writing objects: 100% (9/9), 10.51 KiB | 0 bytes/s, done.
Total 9 (delta 2), reused 3 (delta 0)
remote: Resolving deltas: 100% (2/2)
remote: Processing changes: refs: 1, done
To ssh://openbmc.gerrit/openbmc/skeleton
 ! [remote rejected] HEAD -> refs/for/master (not Signed-off-by author/committer/uploader in commit message footer)
error: failed to push some refs to 'ssh://openbmc.gerrit/openbmc/skeleton'

**Comment by adamliyi** [comment]
@ken1029 , I think you just need to add a line to the bottom of the commit message (using `git commit --amend`)
```
Signed-off-by: Name <email>
```
As the error message shows:
```
not Signed-off-by author/committer/uploader in commit message footer
```

**Comment by ken1029** [comment]
thanks~~
problem solved.

**Comment by williamspatrick** [comment]
'git commit --amend -s' is the preferred way rather than manually creating it yourself. The -s adds the signoff for you.

**Pull request closed without merging**
