### PR TITLE
Add fan control algorithm

### PR DESCRIPTION
**Pull request by Kenthliu**
This change is [Reviewable](https://reviewable.io/reviews/openbmc/skeleton/59)

### CODE REVIEW

**Comment by nkskjames** [comment]
hwmons_barreleye.c is not used anymore.  The hwmon directories are scanned and matched up to entries in Barreleye.py.  So remove that change.  I will remove those files from repository.   Also the SCU changes have already been done in kernel and need to be removed here.  Your new 'info' program should probably go in a different repository.   We should discuss.

**Comment by Kenthliu** [comment]
Thanks for your code review Norm. In v0.6-stable, hwmons_barreleye.c is still there, right?    Setup FUNC_MODE[2:0]  is just a temproray workaround for find out Eth1 loss issue root cause, we will remove that. @ken1029 @johnhcwang  Please note Norm's comment. Thanks.

**Comment by nkskjames** [comment]
yes, the file is still there, but not used.  the func_mode gpio workarounds are now in the kernel. you don't need to do those here.  Also, can you please put each new function or fix into it's own pull request so we can independently review and merge them?  Some items will be easier than others.

**Comment by anoo1** [comment]
Hi Ken, in order to merge this, it needs a little more cleanup of the commit history. Some commits can be squashed, some can be remove like the ones that just revert a previous commit. This will require using "git rebase --interactive". If you need help one of us can help clean up. Let us know.

**Comment by causten** [comment]
how's the git changes coming along?

**Comment by shenki** [comment]
Hi @Kenthliu. We want to get this functionaltiy merged in, but the commits need a bit of work

You need to rebase on the latest master.

You also need to squish your commits down so the history is clean. Pretend you're a new developer reading the output of `git log` like a set of newspaper stories - they should each describe one thing that is being added, with a clear short headline and a more detailed explanation below.

Feel free to ask any questions if you need help.

**Comment by williamspatrick** [comment]
Please submit through Gerrit if needed.

**Pull request closed without merging**
