### PR TITLE
Reformat code with pep8 standards

### PR DESCRIPTION
**Pull request by geissonator**
Just formatting,  no functional changes

---
This change is [Reviewable](https://reviewable.io/reviews/openbmc/skeleton/124)

### CODE REVIEW

**Comment by bradbishop** [comment]
Sorry - should have mentioned last time but you need a COO:
https://github.com/openbmc/docs/blob/master/contributing.md#developers-certificate-of-origin-11

This is what the 'Signed-off-by: Foo Bar <foo@bar.baz>" line you see in the commit tags is for.

**Comment by bradbishop** [comment]
It doesn't matter here because we are moving to Gerrit anyway, but in general it would have better to just refresh your previous pull request rather than starting from scratch, so all the conversation is in a single PR.

**Comment by bradbishop** [comment]
Where did the functional changes go?  You can have more than one commit in a PR....

**Comment by bradbishop** [comment]
Thank you for doing the pep8 cleanup!

**Comment by geissonator** [comment]
oops, still learning best way to do github stuff.  I just created a fresh branch, figured I'd quickly get this merged, rebase against master and then push in my function change in that other branch.  Let me know if you want me get it all under one PR.

Other PR is https://github.com/openbmc/skeleton/pull/120

**Comment by mdmillerii** [comment]
The changelog should identify the files being cleaned up so we don't have to look at the diff to figure that out.

The subject would imply all code was being cleaned up.

**Comment by geissonator** [comment]
Doing it all over in https://github.com/openbmc/skeleton/pull/120

**Pull request closed without merging**
